<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

$dictionary['SSI_Salary_Slip'] = array(
    'table' => 'ssi_salary_slip',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array (
  'sal_basic' => 
  array (
    'required' => false,
    'name' => 'sal_basic',
    'vname' => 'LBL_SAL_BASIC',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '8',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
  'sal_hra' => 
  array (
    'required' => false,
    'name' => 'sal_hra',
    'vname' => 'LBL_SAL_HRA',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '8',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
  'sal_conv' => 
  array (
    'required' => false,
    'name' => 'sal_conv',
    'vname' => 'LBL_SAL_CONV',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '8',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
  'sal_trans' => 
  array (
    'required' => false,
    'name' => 'sal_trans',
    'vname' => 'LBL_SAL_TRANS',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '8',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
  'sal_special' => 
  array (
    'required' => false,
    'name' => 'sal_special',
    'vname' => 'LBL_SAL_SPECIAL',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '8',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
  'sal_medical' => 
  array (
    'required' => false,
    'name' => 'sal_medical',
    'vname' => 'LBL_SAL_MEDICAL',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '8',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
  'ded_pf' => 
  array (
    'required' => false,
    'name' => 'ded_pf',
    'vname' => 'LBL_DED_PF',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '8',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
  'ded_esi' => 
  array (
    'required' => false,
    'name' => 'ded_esi',
    'vname' => 'LBL_DED_ESI',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '8',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
  'ded_loan' => 
  array (
    'required' => false,
    'name' => 'ded_loan',
    'vname' => 'LBL_DED_LOAN',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '8',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
  'ded_professional_tax' => 
  array (
    'required' => false,
    'name' => 'ded_professional_tax',
    'vname' => 'LBL_DED_PROFESSIONAL_TAX',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '8',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
  'ded_tds' => 
  array (
    'required' => false,
    'name' => 'ded_tds',
    'vname' => 'LBL_DED_TDS',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '8',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
  'month_year' => 
  array (
    'required' => false,
    'name' => 'month_year',
    'vname' => 'LBL_MONTH_YEAR',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '50',
    'size' => '20',
  ),
  'sal_gross_earning' => 
  array (
    'required' => false,
    'name' => 'sal_gross_earning',
    'vname' => 'LBL_SAL_GROSS_EARNING',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '8',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
  'sal_gross_deduction' => 
  array (
    'required' => false,
    'name' => 'sal_gross_deduction',
    'vname' => 'LBL_SAL_GROSS_DEDUCTION',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '8',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
  'sal_net_amount' => 
  array (
    'required' => false,
    'name' => 'sal_net_amount',
    'vname' => 'LBL_SAL_NET_AMOUNT',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '8',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
  'net_amount_in_words' => 
  array (
    'required' => false,
    'name' => 'net_amount_in_words',
    'vname' => 'LBL_NET_AMOUNT_IN_WORDS',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'days_worked' => 
  array (
    'required' => false,
    'name' => 'days_worked',
    'vname' => 'LBL_DAYS_WORKED',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '5',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
  'working_days' => 
  array (
    'required' => false,
    'name' => 'working_days',
    'vname' => 'LBL_WORKING_DAYS',
    'type' => 'decimal',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '5',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
  'month' => 
  array (
    'required' => true,
    'name' => 'month',
    'vname' => 'LBL_MONTH',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'month_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'year' => 
  array (
    'required' => true,
    'name' => 'year',
    'vname' => 'LBL_YEAR',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => '2022',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'year_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'financial_year' => 
  array (
    'required' => false,
    'name' => 'financial_year',
    'vname' => 'LBL_FINANCIAL_YEAR',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'inline_edit' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '10',
    'size' => '20',
  ),
),
    'relationships' => array (
),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('SSI_Salary_Slip', 'SSI_Salary_Slip', array('basic','assignable','security_groups'));