<?php 
$GLOBALS["dictionary"]["SSI_Holiday"]["fields"]["day"] = array (
	'required' => false,
	'name' => 'day',
	'vname' => 'LBL_DAY',
	'type' => 'enum',
	'massupdate' => 0,
	'no_default' => false,
	'comments' => '',
	'help' => '',
	'importable' => 'true',
	'duplicate_merge' => 'disabled',
	'duplicate_merge_dom_value' => '0',
	'audited' => false,
	'inline_edit' => true,
	'reportable' => true,
	'unified_search' => false,
	'merge_filter' => 'disabled',
	'len' => '100',
	'size' => '20',
	'options' => 'ssi_day_list',
    'studio' => 'visible',
    'dependency' => false,
);
