<?php 
$dictionary['Document']['fields']['document_type'] = 
array (
  'inline_edit' => '1',
  'required' => true,
  'name' => 'document_type',
  'vname' => 'LBL_DOCUMENT_TYPE',
  'type' => 'dynamicenum',
  'massupdate' => '0',
  'default' => NULL,
  'no_default' => false,
  'comments' => '',
  'help' => '',
  'importable' => 'true',
  'duplicate_merge' => 'disabled',
  'duplicate_merge_dom_value' => '0',
  'audited' => false,
  'reportable' => true,
  'unified_search' => false,
  'merge_filter' => 'disabled',
  'len' => 100,
  'size' => '20',
  'options' => 'document_type_list',
  'studio' => 'visible',
  'dbType' => 'enum',
  'parentenum' => 'category_id',
);

$dictionary['Document']['fields']['amount'] = 
array (
  'required' => false,
  'name' => 'amount',
  'vname' => 'LBL_AMOUNT',
  'type' => 'currency',
  'massupdate' => 0,
  'comments' => '',
  'help' => '',
  'importable' => 'true',
  'duplicate_merge' => 'disabled',
  'duplicate_merge_dom_value' => '0',
  'audited' => 1,
  'reportable' => true,
  'len' => '26,6',
);

$dictionary['Document']['fields']['document_date'] = 
array (
  'required' => false,
  'name' => 'document_date',
  'vname' => 'LBL_DOCUMENT_DATE',
  'type' => 'date',
  'massupdate' => 0,
  'no_default' => false,
  'comments' => '',
  'help' => '',
  'importable' => 'true',
  'duplicate_merge' => 'disabled',
  'duplicate_merge_dom_value' => '0',
  'audited' => false,
  'inline_edit' => true,
  'reportable' => true,
  'unified_search' => false,
  'merge_filter' => 'disabled',
  'size' => '20',
  'enable_range_search' => false,
);

$dictionary['Document']['fields']['month'] = 
array (
  'required' => false,
  'name' => 'month',
  'vname' => 'LBL_MONTH',
  'type' => 'enum',
  'massupdate' => 0,
  'no_default' => false,
  'comments' => '',
  'help' => '',
  'importable' => 'true',
  'duplicate_merge' => 'disabled',
  'duplicate_merge_dom_value' => '0',
  'audited' => false,
  'inline_edit' => true,
  'reportable' => true,
  'unified_search' => false,
  'merge_filter' => 'disabled',
  'len' => 100,
  'size' => '20',
  'options' => 'month_list',
  'studio' => 'visible',
  'dependency' => false,
);
$dictionary['Document']['fields']['year'] =
array (
  'required' => true,
  'name' => 'year',
  'vname' => 'LBL_YEAR',
  'type' => 'enum',
  'massupdate' => 0,
  'no_default' => false,
  'comments' => '',
  'help' => '',
  'importable' => 'true',
  'duplicate_merge' => 'disabled',
  'duplicate_merge_dom_value' => '0',
  'audited' => false,
  'inline_edit' => true,
  'reportable' => true,
  'unified_search' => false,
  'merge_filter' => 'disabled',
  'len' => 100,
  'size' => '20',
  'options' => 'year_list',
  'studio' => 'visible',
  'dependency' => false,
);

$dictionary['Document']['fields']['expense_type'] =
array (
  'required' => false,
  'name' => 'expense_type',
  'vname' => 'LBL_EXPENSE_TYPE',
  'type' => 'enum',
  'massupdate' => 0,
  'no_default' => false,
  'comments' => '',
  'help' => '',
  'importable' => 'true',
  'duplicate_merge' => 'disabled',
  'duplicate_merge_dom_value' => '0',
  'audited' => false,
  'inline_edit' => true,
  'reportable' => true,
  'unified_search' => false,
  'merge_filter' => 'disabled',
  'len' => 100,
  'size' => '20',
  'options' => 'expense_type_list',
  'studio' => 'visible',
  'dependency' => false,
);

$dictionary['Document']['fields']['gst_compliance'] = 
array (
    'name' => 'gst_compliance',
    'vname' => 'LBL_GST_COMPLIANCE',
    'type' => 'bool',
    'default' => '0',
    'audited' => true,
);

$dictionary['Document']['fields']['gst_amount'] = 
array (
  'required' => false,
  'name' => 'gst_amount',
  'vname' => 'LBL_GST_AMOUNT',
  'type' => 'currency',
  'massupdate' => 0,
  'comments' => '',
  'help' => '',
  'importable' => 'true',
  'duplicate_merge' => 'disabled',
  'duplicate_merge_dom_value' => '0',
  'audited' => 1,
  'reportable' => true,
  'len' => '18,2',
);