<?php 
$dictionary['SSI_Leaves']['fields']['month'] = 
array (
  'required' => false,
  'name' => 'month',
  'vname' => 'LBL_MONTH',
  'type' => 'enum',
  'massupdate' => 0,
  'no_default' => false,
  'comments' => '',
  'help' => '',
  'importable' => 'true',
  'duplicate_merge' => 'disabled',
  'duplicate_merge_dom_value' => '0',
  'audited' => false,
  'inline_edit' => true,
  'reportable' => true,
  'unified_search' => false,
  'merge_filter' => 'disabled',
  'len' => 100,
  'size' => '20',
  'options' => 'month_list',
  'studio' => 'visible',
  'dependency' => false,
);
$dictionary['SSI_Leaves']['fields']['year'] =
array (
  'required' => true,
  'name' => 'year',
  'vname' => 'LBL_YEAR',
  'type' => 'enum',
  'massupdate' => 0,
  'no_default' => false,
  'comments' => '',
  'help' => '',
  'importable' => 'true',
  'duplicate_merge' => 'disabled',
  'duplicate_merge_dom_value' => '0',
  'audited' => false,
  'inline_edit' => true,
  'reportable' => true,
  'unified_search' => false,
  'merge_filter' => 'disabled',
  'len' => 100,
  'size' => '20',
  'options' => 'year_list',
  'studio' => 'visible',
  'dependency' => false,
);